# Dockerfile for Node.js server
FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --silent

# Copy the rest of the application code
COPY . .

EXPOSE 4000

CMD ["npm", "run", "start:servera"]
