version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "80:80"  # Serve the React app on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

  servera:
    build:
      context: .
      dockerfile: Dockerfile.servera
    ports:
      - "4000:4000"  # Bind port 4000 on the host to servera
    networks:
      - my-network

  serverb:
    build:
      context: .
      dockerfile: Dockerfile.serverb
    ports:
      - "5001:5000"  # Bind a different host port to serverb to avoid conflicts
    networks:
      - my-network

  serverc:
    build:
      context: .
      dockerfile: Dockerfile.serverc
    ports:
      - "4201:4200"  # Avoid port conflicts
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
